name: Jackett
version: 0.1.1
slug: hassio_jackett
description: An addon to add jackett to hassio
url: https://github.com/cazac9/Jackett
arch:
  - aarch64
webui: http://[HOST]:[PORT:8889]
map:
- config:rw
- share:rw
- ssl
hassio_api: true
host_network: true
auth_api: true
apparmor: false
schema:
  black_hole: str
ports:
  8889/tcp: 8889
ports_description:
  8889/tcp: Port for the web interface
